#cloud-config

users:
- name: ubuntu
  ssh_authorized_keys: []

package_update: true
package_upgrade: true

# 'package_upgrade' may pull newer versions of kernel which require a reboot.
# However, rebooting takes additional time which defeats the purpose of 
# an ephemeral machine for swift concept/code tests.
# package_reboot_if_required: true

packages:
- apt: [avahi-daemon]

runcmd:
- [systemctl, enable, ufw]
- [ufw, allow, from, 192.168.0.0/16]
- [ufw, enable]
- [systemctl, enable, avahi-daemon]