#!/usr/bin/env bash

# set -o errexit   # abort on nonzero exitstatus
# set -o nounset   # abort on unbound variable
# set -o pipefail  # don't hide errors within pipes

# set -euo pipefail



set -x # debug


# Constants
# path="$HOME/.ssh/keys"
readonly ssh_path="test"                            # base dir for the ssh keys
readonly cloud_init_template="cloud-init.yaml"      # template file
readonly key_type="ed25519"                         # ssh-keygen key type
readonly key_name="id_ed25519"                      # private and public key names
                     
# Globals
name=${1:-}                                         # VM and SSH key pair dir name
rand_num="$RANDOM"                                  # Random number to concat with '$name'
now=$(date +"%Y-%m-%d-%H-%M-%S")                    # Current date and time to concat with cloud-init
cloud_init_path="cloud-init-$now.yaml"

# Generate SSH key pair with no passphrase
# Globals: key_type
# Arguments: key_path
generate_keys() {
    local key_path=$1
    ssh-keygen -t "$key_type" -f "$key_path" -N ""
}

# Append cloud-init-`date`.yaml with the public key generated by generate_keys()
# Globals: cloud_init_path
# Arguments: {key_path}.pub
append_cloud_init() {
    local pub_key_path=$1
    local pub_key
    pub_key=$(cat "$pub_key_path")

    sed -i "" "1,/ssh_authorized_keys: \[.*\]/s|ssh_authorized_keys: \[.*\]|ssh_authorized_keys: [$pub_key]|" "$cloud_init_path"
}

# Check if the VM name was provided
if [[ -z "$name" ]]; then
    echo "Usage: $0 <vm-name>"
    exit 1
fi

# Check if the SSH key base path exits
if [[ ! -d "$ssh_path" ]]; then
    echo "SSH key base path does not exist: $ssh_path"
    exit 1
fi


# Check if the template exists and copy it
if [[ -f "$cloud_init_template" ]]; then
    echo "Found the cloud-init template. Copying it"
    cp "$cloud_init_template" "$cloud_init_path"
else
    echo "Didn't find the template file at $cloud_init_template. Exiting."
    exit 1
fi


# TODO: remove the `$final_name` and reassign the `$name` instead.
# TODO?: should I move the template copying logic below (to keep in mind: set -o nounset)
final_name="$name"

if multipass list | awk '{print $1}' | grep -Fxq -- "$name" || [[ -d "${ssh_path}/${name}" ]]; then
    echo "VM name or key directory already exists. Appending a random number."
    final_name="${name}-${rand_num}"
fi

full_path="${ssh_path}/${final_name}"

mkdir "$full_path"

key_path="${full_path}/${key_name}"






# Call the functions
generate_keys "$key_path"
append_cloud_init "${key_path}.pub"
 


# TODO: functionality to set the custom memory and storage paramaters within the multipass command.


# if multipass list | awk '{print $1}' | grep -Fxq -- "$name"; then
#     echo "Machine with this name has been already created. Appending a random number."
#     name="${name}-${rand_num}"
#     multipass launch -n "$name" --cloud-init "$cloud_init_path"
# else
#     multipass launch -n "$name" --cloud-init "$cloud_init_path"
# fi
    

# ssh -i "$key_path" "ubuntu@$name.local"
