name: Lint
on:
  push:
    paths: ['*.sh', '*.bash', 'test/*.sh', 'test/*.bash']
  pull_request:
    paths: ['*.sh', '*.bash', 'test/*.sh', 'test/*.bash']
  workflow_dispatch:

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo to the runner
        uses: actions/checkout@v7
        # Shellcheck is preinstalled on GitHub's Linux runner
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: >-
            test/bats
            test/test_helper/bats-assert
            test/test_helper/bats-support